2024-09-03 00:19:02,694 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Current SDK version is 0.17.7
2024-09-03 00:19:02,694 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Configure stats pid to 90406
2024-09-03 00:19:02,694 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Loading settings from /Users/genereux/.config/wandb/settings
2024-09-03 00:19:02,694 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Loading settings from /Users/genereux/Documents/OPENCORE/DATA_CTF/MSL-Location-Mention-Recognition/approach_5/wandb/settings
2024-09-03 00:19:02,694 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'notebook_name': 'fine-tunne--t5-google.ipynb'}
2024-09-03 00:19:02,694 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-09-03 00:19:02,694 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-03 00:19:02,694 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-09-03 00:19:02,694 INFO    MainThread:90406 [wandb_init.py:_log_setup():524] Logging user logs to /Users/genereux/Documents/OPENCORE/DATA_CTF/MSL-Location-Mention-Recognition/approach_5/wandb/run-20240903_001902-zdyda7zc/logs/debug.log
2024-09-03 00:19:02,694 INFO    MainThread:90406 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/genereux/Documents/OPENCORE/DATA_CTF/MSL-Location-Mention-Recognition/approach_5/wandb/run-20240903_001902-zdyda7zc/logs/debug-internal.log
2024-09-03 00:19:02,694 INFO    MainThread:90406 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x35df9fd10>
2024-09-03 00:19:02,694 INFO    MainThread:90406 [wandb_init.py:init():607] calling init triggers
2024-09-03 00:19:02,694 INFO    MainThread:90406 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {}
2024-09-03 00:19:02,694 INFO    MainThread:90406 [wandb_init.py:init():657] starting backend
2024-09-03 00:19:02,694 INFO    MainThread:90406 [wandb_init.py:init():661] setting up manager
2024-09-03 00:19:02,695 INFO    MainThread:90406 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-09-03 00:19:02,695 INFO    MainThread:90406 [wandb_init.py:init():669] backend started and connected
2024-09-03 00:19:02,699 INFO    MainThread:90406 [wandb_run.py:_label_probe_notebook():1338] probe notebook
2024-09-03 00:19:02,700 INFO    MainThread:90406 [wandb_init.py:init():764] updated telemetry
2024-09-03 00:19:02,743 INFO    MainThread:90406 [wandb_init.py:init():797] communicating run to backend with 90.0 second timeout
2024-09-03 00:19:04,365 WARNING MsgRouterThr:90406 [router.py:message_loop():77] message_loop has been closed
2024-09-03 00:20:33,162 ERROR   MainThread:90406 [wandb_init.py:init():823] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-09-03 00:20:33,163 ERROR   MainThread:90406 [wandb_init.py:init():1235] error in wandb.init()
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1225, in init
    return wi.init()
           ^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 829, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-09-03 00:20:55,163 INFO    MainThread:90406 [wandb_settings.py:_apply_login():1936] Applying login settings: {}
2024-09-03 00:20:55,169 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Current SDK version is 0.17.7
2024-09-03 00:20:55,169 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Configure stats pid to 90406
2024-09-03 00:20:55,170 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Loading settings from /Users/genereux/.config/wandb/settings
2024-09-03 00:20:55,170 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Loading settings from /Users/genereux/Documents/OPENCORE/DATA_CTF/MSL-Location-Mention-Recognition/approach_5/wandb/settings
2024-09-03 00:20:55,170 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'notebook_name': 'fine-tunne--t5-google.ipynb'}
2024-09-03 00:20:55,170 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-09-03 00:20:55,170 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-03 00:20:55,170 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-09-03 00:20:55,170 INFO    MainThread:90406 [wandb_init.py:_log_setup():524] Logging user logs to /Users/genereux/Documents/OPENCORE/DATA_CTF/MSL-Location-Mention-Recognition/approach_5/wandb/run-20240903_002055-ahgmxoyp/logs/debug.log
2024-09-03 00:20:55,170 INFO    MainThread:90406 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/genereux/Documents/OPENCORE/DATA_CTF/MSL-Location-Mention-Recognition/approach_5/wandb/run-20240903_002055-ahgmxoyp/logs/debug-internal.log
2024-09-03 00:20:55,170 INFO    MainThread:90406 [wandb_init.py:init():607] calling init triggers
2024-09-03 00:20:55,170 INFO    MainThread:90406 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {}
2024-09-03 00:20:55,170 INFO    MainThread:90406 [wandb_init.py:init():657] starting backend
2024-09-03 00:20:55,170 INFO    MainThread:90406 [wandb_init.py:init():661] setting up manager
2024-09-03 00:20:55,171 INFO    MainThread:90406 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-09-03 00:20:55,171 INFO    MainThread:90406 [wandb_init.py:init():669] backend started and connected
2024-09-03 00:20:55,176 INFO    MainThread:90406 [wandb_run.py:_label_probe_notebook():1338] probe notebook
2024-09-03 00:20:55,176 INFO    MainThread:90406 [wandb_init.py:init():764] updated telemetry
2024-09-03 00:20:55,207 INFO    MainThread:90406 [wandb_init.py:init():797] communicating run to backend with 90.0 second timeout
2024-09-03 00:21:03,198 WARNING MainThread:90406 [wandb_init.py:init():1229] interrupted
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1225, in init
    return wi.init()
           ^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 800, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-09-03 00:21:59,227 INFO    MainThread:90406 [wandb_settings.py:_apply_login():1936] Applying login settings: {}
2024-09-03 00:21:59,232 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Current SDK version is 0.17.7
2024-09-03 00:21:59,232 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Configure stats pid to 90406
2024-09-03 00:21:59,232 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Loading settings from /Users/genereux/.config/wandb/settings
2024-09-03 00:21:59,232 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Loading settings from /Users/genereux/Documents/OPENCORE/DATA_CTF/MSL-Location-Mention-Recognition/approach_5/wandb/settings
2024-09-03 00:21:59,232 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'notebook_name': 'fine-tunne--t5-google.ipynb'}
2024-09-03 00:21:59,232 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-09-03 00:21:59,232 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-03 00:21:59,233 INFO    MainThread:90406 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-09-03 00:21:59,233 INFO    MainThread:90406 [wandb_init.py:_log_setup():524] Logging user logs to /Users/genereux/Documents/OPENCORE/DATA_CTF/MSL-Location-Mention-Recognition/approach_5/wandb/run-20240903_002159-evjiwiez/logs/debug.log
2024-09-03 00:21:59,233 INFO    MainThread:90406 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/genereux/Documents/OPENCORE/DATA_CTF/MSL-Location-Mention-Recognition/approach_5/wandb/run-20240903_002159-evjiwiez/logs/debug-internal.log
2024-09-03 00:21:59,233 INFO    MainThread:90406 [wandb_init.py:init():607] calling init triggers
2024-09-03 00:21:59,233 INFO    MainThread:90406 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {}
2024-09-03 00:21:59,233 INFO    MainThread:90406 [wandb_init.py:init():657] starting backend
2024-09-03 00:21:59,233 INFO    MainThread:90406 [wandb_init.py:init():661] setting up manager
2024-09-03 00:21:59,234 INFO    MainThread:90406 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-09-03 00:21:59,234 INFO    MainThread:90406 [wandb_init.py:init():669] backend started and connected
2024-09-03 00:21:59,237 INFO    MainThread:90406 [wandb_run.py:_label_probe_notebook():1338] probe notebook
2024-09-03 00:21:59,238 INFO    MainThread:90406 [wandb_init.py:init():764] updated telemetry
2024-09-03 00:21:59,274 INFO    MainThread:90406 [wandb_init.py:init():797] communicating run to backend with 90.0 second timeout
